[package]
name = "FocusNavigation"
authors = ["Roblox"]
version = { workspace = true }
content_root = "src"
files = ["*", "!**/__tests__"]

[dependencies]
EventPropagation = { path = "../event-propagation" }
Utils = { path = "../utils" }

[dev_dependencies]
Collections = { workspace = true }
JestGlobals = { workspace = true }
Jest = { workspace = true }
