[package]
name = "FocusNavigation"
authors = ["Roblox"]
version = "0.1.0"
content_root = "src"
files = ["*", "!**/__tests__"]

[dependencies]
EventPropagation = { path = "../event-propagation" }
ZenObservable = "github.com/roblox/zen-observable-lua@0.8.16-roblox.0"

[dev_dependencies]
Collections = { workspace = true }
JestGlobals = { workspace = true }
Jest = { workspace = true }
