[package]
name = "DemoApp"
authors = ["Roblox"]
version = { workspace = true }
content_root = "src"
files = ["*", "!**/__tests__"]

[dependencies]
ReactFocusNavigation = { path = "../react-focus-navigation" }
InputHandlers = { path = "../input-handlers" }

RoactNavigation = "github.com/roblox/roact-navigation@0.5.4"
ReactRoblox = "github.com/roblox/roact-alignment@17.0.1-rc.18"
React = "github.com/roblox/roact-alignment@17.0.1-rc.18"
Collections = { workspace = true }

[dev_dependencies]
ReactTestingLibrary = "github.com/roblox/react-testing-library-lua@12.1.5"
Rhodium = "github.com/roblox/rhodium@0.4.6"

JestGlobals = { workspace = true }
Jest = { workspace = true }
