site_name: Focus Navigation
site_url: https://roblox.github.io/focus-navigation/
repo_name: Roblox/focus-navigation
repo_url: https://github.com/Roblox/focus-navigation

theme:
  name: material
  palette:
    primary: green
    accent: green

nav:
  - Home: index.md
  - API Reference:
      - React Focus Navigation: api-reference/react-focus-navigation.md
      - Input Handlers: api-reference/input-handlers.md
      - Focus Behaviors: api-reference/focus-behaviors.md
      - Focus Navigation: api-reference/focus-navigation.md
      - Event Propagation: api-reference/event-propagation.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
