site_name: Focus Navigation Documentation
site_url: https://roblox.github.io/focus-navigation/
repo_name: Roblox/focus-navigation
repo_url: https://github.com/Roblox/focus-navigation

theme:
  name: material
  palette:
    primary: 'Light Blue'
    accent: 'Light Blue'

pages:
  - Home: index.md
  - API Reference: api-reference.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences