site_name: Focus Navigation
site_url: https://roblox.github.io/focus-navigation-internal/
repo_name: Roblox/focus-navigation-internal
repo_url: https://github.com/Roblox/focus-navigation-internal

theme:
  name: material
  palette:
    primary: green
    accent: green
  features:
    - navigation.sections
    - navigation.expand

nav:
  - Fundamentals: index.md
  - API Reference:
      - Public API:
          - React Focus Navigation: api-reference/react-focus-navigation.md
          - Focus Navigation: api-reference/focus-navigation.md
          - Input Handlers: api-reference/input-handlers.md
      - Internal API:
          - Focus Behaviors: api-reference/focus-behaviors.md
          - Event Propagation: api-reference/event-propagation.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
