[workspace]
version = "1.3.1"
members = ["modules/*"]

[config]
registry_index = true

[workspace.dependencies]
Collections = "github.com/roblox/luau-polyfill@1.2"
JestGlobals = "github.com/roblox/jest-roblox@3.3.0"
Jest = "github.com/roblox/jest-roblox@3.2.2"
