std = "roblox"

[config]
# Configure selene's linting:
# https://kampfkarren.github.io/selene/usage/configuration.html

[rules]
# remove this once the feature request here is implemented: https://github.com/Kampfkarren/selene/issues/181
global_usage = "allow"
