[package]
name = "ReactFocusNavigation"
authors = ["Roblox"]
version = { workspace = true }
content_root = "src"
files = ["*", "!**/__tests__"]

[dependencies]
FocusNavigation = { path = "../focus-navigation" }
FocusBehaviors = { path = "../focus-behaviors" }
FocusNavigationUtils = { path = "../focus-navigation-utils" }
React = "github.com/roblox/roact-alignment@17.0.1-rc.18"

[dev_dependencies]
ReactTestingLibrary = "github.com/roblox/react-testing-library-lua@12.1.5"
Rhodium = "github.com/roblox/rhodium@0.4.6"
Collections = { workspace = true }
JestGlobals = { workspace = true }
Jest = { workspace = true }
