[package]
name = "EventPropagation"
authors = ["Roblox"]
version = "0.1.0"
content_root = "src"
files = ["*", "!**/__tests__"]

[dependencies]
Utils = { path = "../utils" }

[dev_dependencies]
JestGlobals = { workspace = true }
Jest = { workspace = true }
