[package]
name = "FocusBehaviors"
authors = ["Roblox"]
version = { workspace = true }
content_root = "src"
files = ["*", "!**/__tests__"]

[dependencies]
FocusNavigation = { path = "../focus-navigation" }

[dev_dependencies]
React = "github.com/roblox/roact-alignment@17.0.1-rc.18"
ReactTestingLibrary = "github.com/roblox/react-testing-library-lua@12.1.5"
ReactFocusNavigation = { path = "../react-focus-navigation" }
Rhodium = "github.com/roblox/rhodium@0.4.6"
Utils = { path = "../utils" }
Collections = { workspace = true }
JestGlobals = { workspace = true }
Jest = { workspace = true }
